#pragma once

#ifndef CHESSTYPES_HPP
#define CHESSTYPES_HPP

#include <cstdint>
#include <string>

typedef uint64_t U64;

enum Color
{
	WHITE = 0,
	BLACK = 6,
};

enum PieceType
{
	PAWN,
	KNIGHT,
	BISHOP,
	ROOK,
	QUEEN,
	KING,
};

enum Piece
{
	WHITE_PAWN = WHITE + PAWN,
	WHITE_KNIGHT = WHITE + KNIGHT,
	WHITE_BISHOP = WHITE + BISHOP,
	WHITE_ROOK = WHITE + ROOK,
	WHITE_QUEEN = WHITE + QUEEN,
	WHITE_KING = WHITE + KING,
	BLACK_PAWN = BLACK + PAWN,
	BLACK_KNIGHT = BLACK + KNIGHT,
	BLACK_BISHOP = BLACK + BISHOP,
	BLACK_ROOK = BLACK + ROOK,
	BLACK_QUEEN = BLACK + QUEEN,
	BLACK_KING = BLACK + KING
};

#endif // CHESSTYPES_HPP
